### ISSUE TITLE
真机+模拟器 在Podfile 中如何指定版本？

### ISSUE THREAD

**Issue by 3397307081** [pili-engineering/PLMediaStreamingKit#103]
真机+模拟器 在Podfile 中如何指定版本？

**Comment by Kivenhaoyu** [comment]
pod "PLMediaStreamingKit", :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLMediaStreamingKit/master/PLMediaStreamingKit-Universal.podspec'
注：鉴于目前 iOS 上架，只支持动态库真机，请在 App 上架前，更换至真机版本
