### ISSUE TITLE
ios手机横屏推流  预览画面倒转90度

### ISSUE THREAD

**Issue by monkeyttttt** [pili-engineering/PLMediaStreamingKit#105]
ios手机横屏推流  预览画面倒转90度

**Comment by monkeyttttt** [comment]
在iPhonex上面

**Comment by monkeyttttt** [comment]
![IMG_4123](https://user-images.githubusercontent.com/4243863/65105846-e2bad780-da08-11e9-8db7-bba0ce219f1f.PNG)
 手机系统版本12.4

**Comment by HeraShowFeng** [comment]
应该是开启采集是 PLVideoCaptureConfiguration 配置采集摄像头选装方向的问题，调整成与预览画面的设备显示方向一致即可

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by myiosemail** [comment]
请问解决了吗？

**Comment by monkeyttttt** [comment]
更新最新SDK已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pili-engineering/PLMediaStreamingKit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月2日(星期三) 下午3:28
收件人:&nbsp;"pili-engineering/PLMediaStreamingKit"<PLMediaStreamingKit@noreply.github.com&gt;;
抄送:&nbsp;"浅水游龙"<505358119@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pili-engineering/PLMediaStreamingKit] ios手机横屏推流  预览画面倒转90度 (#105)





 
请问解决了吗？
