### ISSUE TITLE
demo下载编译通过 真机无法运行报错崩溃

### ISSUE THREAD

**Issue by pzcyl** [pili-engineering/PLMediaStreamingKit#107]
objc[815]: Class RTCCVPixelBuffer is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x20a400720) and /private/var/containers/Bundle/Application/F88FEE41-A34F-45E8-9EEA-AE61493D85F7/QNRTCKitDemo.app/Frameworks/QNRTCKit.framework/QNRTCKit (0x107561340). One of the two will be used. Which one is undefined.
WARN : BSG_KSCrashSentry.c (107): BSG_KSCrashType bsg_kscrashsentry_installWithContext(BSG_KSCrash_SentryContext *, BSG_KSCrashType, void (*)(void)): KSCrash: App is running in a debugger. Only user reported events will be handled.
2019-12-09 13:39:05.801894+0800 QNRTCKitDemo[815:121874] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug'
*** First throw call stack:
(0x1c20c980c 0x1c1df1fa4 0x1c1fbef84 0x1c647d3b4 0x1c63faeb8 0x1c23a0914 0x104b299c8 0x104b295f8 0x104b2bbf8 0x104b2b3f8 0x1c5b14d4c 0x1c5b1985c 0x1c5a8b780 0x1c5a8ba8c 0x1c5a8c8c0 0x1c5a8dc04 0x1c5a710dc 0x1c65c7604 0x1c8b1578c 0x1c8b1b908 0x1c8b26528 0x1c8a6eed0 0x1c8a98bbc 0x1c6149bac 0x1c20475f8 0x1c2046d98 0x1c2042014 0x1c20418a0 0x1cbf99328 0x1c6132740 0x104b41540 0x1c1ecc360)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Kivenhaoyu** [comment]
你好，这是由于 iOS 13 系统升级导致的问题，可以尝试我们的新版本
