### ISSUE TITLE
iOS13.0系统上推流时报错

### ISSUE THREAD

**Issue by 726491400** [pili-engineering/PLMediaStreamingKit#108]
iOS13.0系统上推流时报错 Assertion failure in -[FBSSerialQueue assertOnQueue] 并且闪退

**Comment by Kivenhaoyu** [comment]
你好，麻烦提供以下信息，方便我们进一步定位：
 SDK 的版本号
demo 是否可复现此问题
具体的复现步骤
本地 log 日志
