### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shangqianForFun** [pili-engineering/PLMediaStreamingKit#11]
偶尔出现关闭播放器 pop到上一个控制器，  仍然能听到直播声音

**Comment by hzwangsiyu** [comment]
PLMediaStreamingKit 是推流端，但是听你描述的是播放端的情况，能给到更详细的描述吗？

**Comment by hutuyingxiong** [comment]
pod install会出现问题

**Comment by huangdeheng** [comment]
@hutuyingxiong 麻烦给到问题的具体信息？

**Comment by huangdeheng** [comment]
linked to [#26](https://github.com/pili-engineering/PLMediaStreamingKit/issues/26)
