### ISSUE TITLE
Archive 失败：Failed to verify bitcode in PLMediaStreamingKit.framework/PLMediaStreamingKit:

### ISSUE THREAD

**Issue by ONEWJ** [pili-engineering/PLMediaStreamingKit#110]
cocoapods集成 2.3.5版本
真机运行ok
Archive失败：
Failed to verify bitcode in PLMediaStreamingKit.framework/PLMediaStreamingKit:
error: Linker option verification failed for bundle /var/folders/g0/sfmcxr3d3l1fk3r_npny_nfw0000gp/T/PLMediaStreamingKitWc_wnv/PLMediaStreamingKit.arm64.xar (unrecognized arguments: -platform_version iOS 8.0.0 13.2.0)

**Comment by b1003572686** [comment]
你好这个问题解决了吗 我也是这个问题

**Comment by HeraShowFeng** [comment]
需要关闭 App 工程的 bitcode
