### ISSUE TITLE
运行崩溃

### ISSUE THREAD

**Issue by blacklsxy** [pili-engineering/PLMediaStreamingKit#112]
dyld: Library not loaded: @rpath/HappyDNS.framework/HappyDNS
  Referenced from: /private/var/containers/Bundle/Application/DCF22BE4-7846-4F28-BEF9-0FBD2EE2D7DB/PLMediaStreamingKitDemo.app/PLMediaStreamingKitDemo
  Reason: no suitable image found.  Did find:

**Comment by HeraShowFeng** [comment]
检查下引用的地址是否正确
