### ISSUE TITLE
stream:nil

### ISSUE THREAD

**Issue by JiaMamjj** [pili-engineering/PLMediaStreamingKit#119]
仿照  https://developer.qiniu.com/pili/sdk/3780/PLMediaStreamingKit-quick-start 写的开始，
但是提示 PLStreamStartStateSessionConnectStreamError
想问下，用推流地址了，还需要配置 stream？
推流不成功

**Comment by HeraShowFeng** [comment]
建议检查下推流地址，API 初始化 stream 是非必须配置
