### ISSUE TITLE
initEnv()初始化运行环境，是否会影响引入的其他的推流SDK？

### ISSUE THREAD

**Issue by OrangesChen** [pili-engineering/PLMediaStreamingKit#120]
项目中已经引入了腾讯云推流SDK，考虑引入七牛云的SDK，根据不同的场景使用不同的SDK进行推流，如果在appdelegate中调用initEnv()初始化环境，但是使用的推流SDK是腾讯的，会影响到其他推流的操作么？不知道initEnv()中做了些什么操作？

**Comment by HeraShowFeng** [comment]
不会影响其他 sdk，只是初始化 sdk 内部环境
