### ISSUE TITLE
后台推流

### ISSUE THREAD

**Issue by YuzeHe** [pili-engineering/PLMediaStreamingKit#13]
请问下后台推流是怎么开启，我看了 CameraStreamingKit 和 StreamingKit 里的头文件，没有找到关于后台推流。

**Comment by huangdeheng** [comment]
SDK层面不需要额外设置，只需在Xcode工程开启 `Background Modes` 权限；另后台只支持音频推流。

**Comment by YuzeHe** [comment]
噢。了解了，谢谢！
