### ISSUE TITLE
如何判定主播离开

### ISSUE THREAD

**Issue by YuzeHe** [pili-engineering/PLMediaStreamingKit#14]
现在想做一个类似映客花椒主播离开时的功能，就是主播进入后台时，会给在房间里的人发一条“主播暂时离开中...”这样类似的信息。
但我发现咱们这个当推流端每次切换应用进入后台时，state 会从 “ Disconnecting -> Disconnected -> Connecting -> Connecting ”走两遍，然后开始推
"Stream Status:
	Video FPS: 0.0
	Audio FPS: 0.0
	TotalBitrate: 0.0 bps(0.0 KB/s)"
疑问就来了，为什么会走两遍呢？ 
还有你们觉得应该是屏蔽其中一遍，在主播状态进入“Disconnecting”时给观众发送，还是应该程序走“applicationDidEnterBackground”时给观众发送。来点建议吧~ 七牛云开发帅哥们

**Comment by huangdeheng** [comment]
这个功能建议由你们的业务服务器来完成，主播进入后台时向业务服务器发送通知，业务服务器再向观众广播，不应将这个逻辑绑定在流的状态上。
此外在推流时切换到后台，正常并不会出现你说的state变化过程，你是否有做了些restart操作？建议运行下我们的demo试试。
