### ISSUE TITLE
希望能最低支持iOS7.0

### ISSUE THREAD

**Issue by caizetong** [pili-engineering/PLMediaStreamingKit#2]
ld: warning: object file (/Users/cc/Desktop/MKsvn/HuaSeHui/SourceCode/iOS/JiaJuYuan/Pods/PLMediaStreamingKit/Pod/Library/libPLMediaStreamingKit.a(MuseRealTimeProcessor.o)) was built for newer iOS version (8.0) than being linked (7.0)
编译后有一堆这样的警告，希望下个版本能解决。

**Comment by hzwangsiyu** [comment]
下个版本将会解决
