### ISSUE TITLE
在我的项目中使用[mediaSession stopsreaming]的时候崩溃

### ISSUE THREAD

**Issue by Ryeagle** [pili-engineering/PLMediaStreamingKit#21]
新建一个工程，同样的代码不会崩溃
<img width="1377" alt="2016-10-21 1 19 39" src="https://cloud.githubusercontent.com/assets/9208656/19587469/1293af9e-9791-11e6-973a-9bd78510953a.png">
<img width="704" alt="2016-10-21 1 19 27" src="https://cloud.githubusercontent.com/assets/9208656/19587509/515ce6aa-9791-11e6-9f37-32d281566602.png">
<img width="1272" alt="2016-10-21 1 19 11" src="https://cloud.githubusercontent.com/assets/9208656/19587508/5157bdba-9791-11e6-9d9a-1134acd5e327.png">

**Comment by Ryeagle** [comment]
是我的项目中的什么东西冲突了吗？我该怎么找到？

**Comment by huangdeheng** [comment]
@Ryeagle 建议检查一下你的项目中与 demo 工程中的调用流程的差异，还有就是调用线程是否有不同

**Comment by Ryeagle** [comment]
@huangdeheng 
一模一样的代码
之前PLPlayer与我们自己写的推流库冲突了，也遇到了这样的问题，我把PLPlayer降级成2.1.0就能用了。
现在是PLMediaStreamingKit不知道与什么冲突了

**Comment by lawder** [comment]
你们项目中用了 librtmp 吗？

**Comment by Ryeagle** [comment]
对，使用了。但是我已经删除了

**Comment by lawder** [comment]
把工程 clean 一下，同时把 DerivedData 删掉后再试试。

**Comment by Ryeagle** [comment]
@lawder
试了，不灵。。。

**Comment by huangdeheng** [comment]
你们工程中是用 CocoaPods 引入 PLMediaStreamingKit 的吗？看一下是什么版本，还有也贴一下 pili-librtmp 的版本

**Comment by Ryeagle** [comment]
@huangdeheng 我现在更新PLPlayer到2.30也会遇到依赖错误
<img width="1433" alt="2016-10-21 2 39 34" src="https://cloud.githubusercontent.com/assets/9208656/19589083/b2b7d210-979c-11e6-957b-b2bba8862f09.png">

**Comment by Ryeagle** [comment]
在demo工程中，可以更新到最新的PLPlayer，也可以正常跑推流程序，关闭推流。。。

**Comment by huangdeheng** [comment]
@Ryeagle Pod 的版本号应该没问题，但是看你截图的调用栈，最终调到了 RTMPError_Free，正常是 PILI_RTMPError_Free，感觉还是链接出错导致的，建议检查一下你们原来的 librtmp 库是否真的清理干净，或者试一下删掉 pod 重新 install

**Comment by Ryeagle** [comment]
@huangdeheng 
删掉pod，还是不灵
我们工程的pod使用的use_frameworks
会不会跟这个有关系？

**Comment by Ryeagle** [comment]
@huangdeheng 
我找到原因了，播放库PLPLayerKit使用use_frameworks！方式就会崩溃
怎么破？

**Comment by Ryeagle** [comment]
@huangdeheng 
我找到原因了，我们项目中使用的是use_frameworks，动态编译的方式
PLPlayerKit与PLMediaStreamKit发生了冲突。
所以PLPlayerKit只好使用静态编译方式编译好了，再手动拖进去

**Comment by huangdeheng** [comment]
@Ryeagle 使用我们的 demo 加上 use_frameworks 选项会这样么？

**Comment by Ryeagle** [comment]
@huangdeheng 
我没用你们的demo试，用我们的demo试了会崩溃（之前静态编译是不会崩溃的），你们的demo也应该会崩溃。
动态编译的时候，链接出现错误。这就是之前我们自己的音频推流库会与你们的PLPlayer最新的库会产生冲突的原因

**Comment by Ryeagle** [comment]
@huangdeheng 当然，如果你们的demo中没有使用PLPlayerKit，动态静态编译都不会崩溃

**Comment by huangdeheng** [comment]
@Ryeagle  嗯，我们这边再试下集成 PLPlayerKit 并使用 use_frameworks 的情况，如果出现类似 crash，会进行修复的
