### ISSUE TITLE
CocoaPods安装时，报错 [!] Unable to find a specification for `PLMediaStreamingKit`，我又试过安装其它的框架，完全没问题，直接pod search也搜不到

### ISSUE THREAD

**Issue by wenbofeng** [pili-engineering/PLMediaStreamingKit#23]
<img width="438" alt="2016-10-28 4 57 48" src="https://cloud.githubusercontent.com/assets/13327705/19800967/bca91cf0-9d2f-11e6-8a48-461452327fe9.png">

**Comment by huangdeheng** [comment]
@wenbofeng 请重新运行 `pod setup` 和 `pod update`，并确保该操作正确完成

**Comment by wenbofeng** [comment]
试过了，也不行，我以为是我写的名字不对，用pod搜也搜不到

**Comment by wenbofeng** [comment]
其它的框架就可以@hunagdeheng

**Comment by huangdeheng** [comment]
@wenbofeng 应该是你的 CocoaPods Specs 没下载完全，可以到 `~/.cocoapods/repos/master/Specs` 中，执行 `ls | grep PLMedia*`，若为空，则需重新 update CocoaPods

**Comment by lawder** [comment]
另外，执行 pod repo 命令看下你是否更换过源。

**Comment by wenbofeng** [comment]
@huangdeheng 执行 ls | grep PLMedia*，返回空，我需要重新安装cocoaPods?    @lawder 另外执行pod repo显示 为
- Type: git (master)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/apple/.cocoapods/repos/master

**Comment by huangdeheng** [comment]
@wenbofeng 可把 ~/.cocoapods 目录删除，重新执行 `pod setup`，这个过程会比较久

**Comment by wenbofeng** [comment]
好的，我试试 ~_~

**Comment by wenbofeng** [comment]
@huangdeheng 还在更新，我想问下 在这个目录~/.cocoapods/repos/master/Specs没找到，是因为我的版本老，当时没收录PLMediaStreamingKit的原因吗？还有cocoapods这个的包有多少M? 求教

**Comment by huangdeheng** [comment]
@wenbofeng 是你 CocoaPods 的仓库数据太旧，没有 PLMediaStreamingKit 的 spec。CocoaPods 的仓库很大，几百 M，建议用 VPN 下。

**Comment by wenbofeng** [comment]
下了一晚上终于解决了，谢谢两位
