### ISSUE TITLE
swift could not install by cocoapods

### ISSUE THREAD

**Issue by cherishloveyou** [pili-engineering/PLMediaStreamingKit#33]
target has transitive dependencies that include static binaries pili-ffmpeg,please support framework

**Comment by YuzeHe** [comment]
+ 1

**Comment by YuzeHe** [comment]
+ 1

**Comment by YuzeHe** [comment]
+1

**Comment by cherishloveyou** [comment]
a month past

**Comment by xuanyi0627** [comment]
+1

**Comment by betallcoffee** [comment]
update PLPlayerKit to 2.4.0 
or not add  use_frameworks! in podfile
or manual import PLPlayerKit not use cocospod
