### ISSUE TITLE
PLPlayerKit (2.2.4) 

### ISSUE THREAD

**Issue by shangqianForFun** [pili-engineering/PLMediaStreamingKit#35]
我正在基于PLPlayer 定制一个播放器，请问一下 有没有类似 缓冲进度的API？ 类似 AVPlayer 的 playableDuration

**Comment by huangdeheng** [comment]
@shangqianForFun 请在 https://github.com/pili-engineering/PLPlayerKit/issues  这里提 Player 的 issue
