### ISSUE TITLE
推流过程中，调用系统相机，画面卡住

### ISSUE THREAD

**Issue by seanxux** [pili-engineering/PLMediaStreamingKit#45]
在推流过程中，调用系统的拍照功能，然后回到直播画面，画面就卡住不动了，有什么解决办法吗？
尝试过调用一次toggleCamera，画面就正常了，有别的正常解决方案吗？

**Comment by helinyu** [comment]
同样出现这个问题，在ios 8上

**Comment by lawder** [comment]
调用系统的拍照功能前后调用 stopCaptureSession 和 startCaptureSession 试试。 @helinyu @seanxux

**Comment by seanxux** [comment]
@lawder 加了stopCaptureSession 和 startCaptureSession，一切正常了，多谢

**Comment by helinyu** [comment]
@seanxux ,你的事所有的ios版本上有这个问题，还是只在一个版本上有这个问题？你如何添加？截图看看？

**Comment by seanxux** [comment]
@helinyu 类似这样加个小逻辑
`- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    
    if (self.sessionCapturePaused) {
        [self.session startCaptureSession];
        [self setSessionCapturePaused:NO];
    }
}

- (void)viewWillDisappear:(BOOL)animated
{
    [super viewWillDisappear:animated];
    
    [self.session stopCaptureSession];
    [self setSessionCapturePaused:YES];
}`

**Comment by seanxux** [comment]
遇到了新问题，现在stopCaptureSession ，再startCaptureSession以后，前置摄像头一切正常。
但是后置摄像头推流会出问题，推流的预览画面正常，拉流端视频好像只有左上角一小部分了，另外偶尔画面颜色会变，画质也会变差。
求解。

**Comment by lawder** [comment]
已解决。
