### ISSUE TITLE
推流的时候总是输出： [PLStreamingSession] cannot push pixelbuffer since last pixelbuffer is still on going

### ISSUE THREAD

**Issue by helinyu** [pili-engineering/PLMediaStreamingKit#47]
这个问题怎么解决？

**Comment by RegenHo** [comment]
我也有同样的问题，还没有解决呢

**Comment by hanweixing** [comment]
同样mark一下，升级到最新的库也是这样，

**Comment by hanweixing** [comment]
[W] Pili-Streaming cannot push pixelbuffer since last pixelbuffer is still on going -[PLStreamingSession pushPixelBuffer:completion:] PLStreamingSession.m:885

**Comment by shuaiwang007** [comment]
求解决，上一次开播关播的时候调了destroy，但是推流时一直报这个错

**Comment by lawder** [comment]
在 App 资源占用过高导致上一帧来不及完成编码等相关操作时就会打印这条日志，其实影响不大，可以忽略。
