### ISSUE TITLE
支持 小视频录制吗？

### ISSUE THREAD

**Issue by lubaoyilang** [pili-engineering/PLMediaStreamingKit#52]
录制小视频，然后 实时美颜，滤镜，最后生成 视频，上传到七牛云存储。

**Comment by depthlove** [comment]
PLShortVideoKit 是七牛推出的一款适用于 iOS 平台的短视频 SDK，提供了包括美颜、滤镜、水印、断点录制、分段回删、视频编辑、混音特效、视频剪辑、本地转码、视频上传在内的多种功能，支持高度定制以及二次开发。
iOS:   https://github.com/pili-engineering/PLShortVideoKit
Android:  https://github.com/pili-engineering/PLDroidShortVideo
