### ISSUE TITLE
在模拟器报错 - PLMediaStreamingKit, 2.1.6

### ISSUE THREAD

**Issue by su350380433** [pili-engineering/PLMediaStreamingKit#58]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PLVideoStreamingConfiguration", referenced from:
      objc-class-ref in AnchorLiveSession.o
  "_OBJC_CLASS_$_PLCameraStreamingSession", referenced from:
      objc-class-ref in AnchorLiveSession.o
  "_OBJC_CLASS_$_PLAudioStreamingConfiguration", referenced from:
      objc-class-ref in AnchorLiveSession.o
  "_OBJC_CLASS_$_PLAudioCaptureConfiguration", referenced from:
      objc-class-ref in AnchorLiveSession.o
  "_OBJC_CLASS_$_PLVideoCaptureConfiguration", referenced from:
      objc-class-ref in AnchorLiveSession.o
  "_OBJC_CLASS_$_PLStreamingEnv", referenced from:
      objc-class-ref in AnchorLiveSession.o
  "_OBJC_CLASS_$_PLStream", referenced from:
      objc-class-ref in AnchorLiveSession.o
  "_kPLVideoStreamingQualityMedium1", referenced from:
      -[AnchorLiveSession VideoStreamConfFromLiveQuality:] in AnchorLiveSession.o
  "_kPLVideoStreamingQualityMedium2", referenced from:
      -[AnchorLiveSession VideoStreamConfFromLiveQuality:] in AnchorLiveSession.o
  "_kPLVideoStreamingQualityMedium3", referenced from:
      -[AnchorLiveSession VideoStreamConfFromLiveQuality:] in AnchorLiveSession.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by su350380433** [comment]
真机可以正常跑起来，求救

**Comment by lawder** [comment]
更新到 2.2.0 试试。
