### ISSUE TITLE
使用pod无法加载

### ISSUE THREAD

**Issue by JoshuaFeng5** [pili-engineering/PLMediaStreamingKit#63]
[!] Unable to find a specification for `PLMediaStreamingKit`

这是pod install 之后发生的结果, 是没有更新吗, 还是怎样, 无法通过pod加载吗

**Comment by missljl** [comment]
Downloading dependencies
Installing HappyDNS (0.3.10)
Installing PLMediaStreamingKit (2.2.5)
一直这样 加载其他库完全没问题，卡在这理1个小时了。
Podfile文件
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
target ‘zhibo’ do
pod 'PLMediaStreamingKit'
end
