### ISSUE TITLE
Xcode 9 Beta3编译不过

### ISSUE THREAD

**Issue by wujianbotju** [pili-engineering/PLMediaStreamingKit#69]
类QNNPing.m 第93行到103行，check_compile_time调用，
error: expected parameter declarator
check_compile_time(sizeof(IPHeader) == 20);
....
....
可能解决方法：check_compile_time中的参数全部添加括号，如
check_compile_time(sizeof(IPHeader) == 20);
改为
check_compile_time((sizeof(IPHeader) == 20));

**Comment by KiritoBeater** [comment]
修改check_compile_time为__Check_Compile_Time可行。

**Comment by jabez1314** [comment]
是版本不更新了么？

**Comment by jabez1314** [comment]
https://github.com/qiniu/iOS-netdiag/releases 这个已经更新了
