### ISSUE TITLE
Xcode 9正式版问题

### ISSUE THREAD

**Issue by zhouxl** [pili-engineering/PLMediaStreamingKit#74]
这个Podspec里的依赖库的版本没有相应的更新，实际已经更新，导致xcode 9编译不过

**Comment by huibenyuanchuang** [comment]
那怎么破

**Comment by Liuhuan247** [comment]
Pod还不更新吗？

**Comment by heyange2002** [comment]
Pod的QNNetDiag依赖什么时候能更新到 0.0.6 ?  Xcode 9 下无法编译

**Comment by depthlove** [comment]
请使用最新版本 https://github.com/pili-engineering/PLMediaStreamingKit/releases
