### ISSUE TITLE
[PLStreamingSession startWithPushURL:feedback] 崩潰問題

### ISSUE THREAD

**Issue by g761007** [pili-engineering/PLMediaStreamingKit#80]
自從更新了2.3.3開始，就會零星偶發這崩潰問題
可以確定的是我們確實有給 Stream URL
數量雖然不多但在報告中的一直有出現所以還是回報告看看
看有沒有人也有遇到
再麻煩大神查看看問題
感謝

PLStreamingSession.m line 1865
-[PLStreamingSession URLAddDomain:]

<img width="977" alt="2017-11-17 9 31 36" src="https://user-images.githubusercontent.com/170883/32924922-2ba05b9a-cb7a-11e7-8b87-f0ea8f79957b.png">

**Comment by lawder** [comment]
这个问题是由给了空的 URL 引起的，请重新检查下。
