### ISSUE TITLE
PLMediaStreamingKit当前版本与PLPlayerKit3.0.0以上版本的libcrypto、libssl .a 文件冲突

### ISSUE THREAD

**Issue by dearbar** [pili-engineering/PLMediaStreamingKit#81]
1，PLMediaStreamingKit当前版本与PLPlayerKit3.0.0以上版本的libcrypto、libssl .a 文件冲突
2，按照PLPlayerKit官方文档的提示，导入动态库依然报错。
请问，之后会有PLMediaStreamingKit版本升级与现在最新版的PLPlayerKit兼容么？

希望能给出好的解决方式，并有详细步骤。谢谢！

**Comment by notePads** [comment]
同求....

**Comment by depthlove** [comment]
使用 2.3.0 及以上版本，就可以解决冲突问题
