### ISSUE TITLE
添加滤镜

### ISSUE THREAD

**Issue by daomoer** [pili-engineering/PLMediaStreamingKit#83]
- (CVPixelBufferRef)mediaStreamingSession:(PLMediaStreamingSession *)session cameraSourceDidGetPixelBuffer:(CVPixelBufferRef)pixelBuffer{
}
在此方法中怎么结合GPUimage添加自定义滤镜

**Comment by depthlove** [comment]
将数据导入 GPUImage 接收口， 返回 return GPUImage 输出处理后的数据。难点在于，需要实现一个能接收 CVPixelBufferRef 数据的GPUImage 类，将这个类加入 GPUImage 的响应链中。
