### ISSUE TITLE
Demo编译报错

### ISSUE THREAD

**Issue by billlk123** [pili-engineering/PLMediaStreamingKit#86]
下载下来的Demo编译报错，
<img width="703" alt="2018-02-08 15 20 32" src="https://user-images.githubusercontent.com/12571530/35960201-bf209b50-0ce3-11e8-92ba-aa4e152357ba.png">
这是什么原因

**Comment by KeymonWong** [comment]
这个问题我也遇到了 为什么没人回答？我搜了好多，都没有解决

**Comment by KeymonWong** [comment]
这个问题 我大概知道原因了，之前版本 好像都是 .a 的静态库，最新版本好像是动态库，在模拟器下 编译不通过，而在真机下编译时通过的，请问7牛的开发者 能不能 生成 pod 导入时候，默认是 真机和模拟器合并之后的 framework 啊？

**Comment by depthlove** [comment]
2018-03-13，周二，会发布 v2.3.1 版本，支持模拟器调试。到时详细内容见 readme 说明。
