### ISSUE TITLE
The RTC Library Not Found

### ISSUE THREAD

**Issue by anddygon** [pili-engineering/PLMediaStreamingKit#87]
按照文档说明操作，推流拉流都正常，但是调用连麦self.session.startConference(xxxx)报如下错误

Error Domain=PLRTCStreamingErrorDomain Code=-3012 "The RTC Library Not Found" UserInfo={NSLocalizedDescription=The RTC Library Not Found

podfile如下
pod 'PLMediaStreamingKit'
pod 'PLPlayerKit'
pod 'pili-librtmp'
pod 'QNNetDiag'
pod 'HappyDNS'

实在不知道问题在哪，帮忙看下

**Comment by depthlove** [comment]
支持连麦，还需要加入连麦 SDK 库，详细内容可查阅七牛开发者中心的文档 https://developer.qiniu.com
