### ISSUE TITLE
videoCaptureConfiguration切换

### ISSUE THREAD

**Issue by seanxux** [pili-engineering/PLMediaStreamingKit#9]
1.8+版本
`- (void)reloadVideoStreamingConfiguration:(PLVideoStreamingConfiguration *)videoStreamingConfiguration videoCaptureConfiguration:(PLVideoCaptureConfiguration *)videoCaptureConfiguration DEPRECATED_ATTRIBUTE;`

2.0+版本
`- (void)reloadVideoStreamingConfiguration:(PLVideoStreamingConfiguration *)videoStreamingConfiguration;`

1.8的版本提供了第一个方法，2.0版本这个方法过期了，没有了videoCaptureConfiguration参数，请问现在怎么切换videoCaptureConfiguration

**Comment by hzwangsiyu** [comment]
现在我们将 'videoCaptureConfiguration' 中的参数都移到了 'PLCameraStreamingSession' 中，可以直接设置相关的参数，不要 reload
