### ISSUE TITLE
PLPlayerKit 如何兼容模拟器+真机运行

### ISSUE THREAD

**Issue by weiwei1991** [pili-engineering/PLMediaStreamingKit#91]
这是模拟器运行后的的错误：
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PLPlayer", referenced from:
。。。。。。。。。。。
Can you give me an answer as soon as possible? Thank you very much!

**Comment by depthlove** [comment]
PLPlayerKit 的问题可以到 https://github.com/pili-engineering/PLPlayerKit/issues 留言。
PLPlayerKit 在 3.2.1 版本中已经支持真机+模拟器版本，详细见 https://github.com/pili-engineering/PLPlayerKit/blob/master/README.md 
若需要使用模拟器 + 真机，则改用如下配置
pod "PLPlayerKit", :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLPlayerKit/master/PLPlayerKit-Universal.podspec'

PLMediaStreamingKit 在最新的版本 2.3.1 已经支持真机+模拟器版本，详细见 https://github.com/pili-engineering/PLMediaStreamingKit/blob/master/README.md
默认为真机版
若需要使用模拟器 + 真机版，则改用如下配置
pod "PLMediaStreamingKit", :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLMediaStreamingKit/master/PLMediaStreamingKit-Universal.podspec'

**注意：鉴于目前 iOS 上架，只支持动态库真机，请在 App 上架前，更换至真机版本**

**Comment by depthlove** [comment]
@weiwei1991 以上信息可以解决你遇到的真机+模拟器调试的问题
