### ISSUE TITLE
Url is invalid

### ISSUE THREAD

**Issue by Ollie-NTP** [pili-engineering/PLMediaStreamingKit#92]
Hello, I installed your library in my react project. When I use the "broadcast" screen, the camera shows the image but it cannot push the stream, in android console I recived a message like " E/Muxer: PLMuxer.prepare():Url is invalid => rtmp://192.168.20.164/play " and " E/Muxer: Init streaming core failed. " Can you help me with this issue?

**Comment by geeklok** [comment]
Thank you for using our product, this is an Android related problem you encountered, which repo should be https://github.com/pili-engineering/PLDroidMediaStreaming.
Before using our SDK, you must contact our business advisor first, this is our website for Live Streaming product: https://www.qiniu.com/en/products/pili
