### ISSUE TITLE
PLMediaStreamingSession推流iPhoneX crash

### ISSUE THREAD

**Issue by OliviaDong2013** [pili-engineering/PLMediaStreamingKit#94]
已经更新PLMediaStreamingKit到最新版本（2018.5.22更新到自己的项目中），
然而：
PLMediaStreamingSession的startStreamingWithPushURL开始推流大概5秒之后程序闪退，
其他平台运行良好，仅在iPhoneX上crash，log如下：
Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIStatusBar_Modern 0x155e07f00> valueForUndefinedKey:]: this class is not key value coding-compliant for the key foregroundView.'
还请开发团队看一下能否尽快修复。
谢！

**Comment by depthlove** [comment]
@OliviaDong2013 Got. We will be check it.

**Comment by depthlove** [comment]
@OliviaDong2013 We solved it on 13 Oct 2017. You need to use the latest version.

**Comment by OliviaDong2013** [comment]
Was failed on updating under MacOS 10.13.4 High Sierra with Ruby 2.0, did not notice that...
Updated PLMediaStreamingKit to the latest version 2.3.1 today, and every thing just works fine.
Thanks a lot. :)
